### ISSUE TITLE
what does the option singleplayer server view distance do

### ISSUE THREAD

**Issue by catmanday** [Johni0702/bobby#110]
what does the option singleplayer server view distance do, i have tried it on and off but id doesn't seem to make any difference what is it meant to do and what does it do?
![image](https://user-images.githubusercontent.com/86985923/184893846-5c2f80b1-ce72-400d-bf7b-b2df7fa72107.png)

**Comment by Johni0702** [comment]
Singleplayer is internally just running an integrated server. By default the view-distance of that integrated server (that's roughly the distance of chunks it loads/generates, simulates/updates and sends to the client) is set to the same as the client's render distance (that's the distance within which the client displays chunks).
With bobby however it can make sense to use a server view-distance lower than your render distance because the difference can be loaded from bobby's cache (which is generally much quicker to load and doesn't have any simulation cost). And that's what this setting does if it's set to any value other than 0.
If you just stand in the same spot or move around chunks bobby has already cached, then you should see no difference (except there will be less entities because less chunks are actually loaded and bobby doesn't cache entities, only blocks), but if you move into an area where you haven't been before, you'll notice that the distance of chunks your client receives will be much smaller than your configured render distance (assuming you set the setting to a much lower value).
