### ISSUE TITLE
Starlight Modrinth:Maven Integration 'Cannot fetch'

### ISSUE THREAD

**Issue by ProfLS** [Johni0702/bobby#115]
Attempted to try and tweak some under the hood stuff for efficiency, however ran into difficulty getting the maven script to fetch starlight for the dependencies.  

Ended up having to comment out the compile script `modCompileOnly` for starlight just to build the project.. 

Possibly something up with the version string val `$starlightVersion`, since Starlight isn't following that format for some reason.  Not sure, but either way, the maven script integration needs some tweaking/updating.

**Comment by Johni0702** [comment]
Is this still an issue? It builds (and downloads starlight) just fine for me, so I'm guessing the Modrinth Maven server just had some issues while you were trying to build.

**Comment by ProfLS** [comment]
Just checked again, and I think it's an issue with android studio's maven plugin implementation.  Tried it again with VScode and got it to build.  Should be fine now

**Comment by Johni0702** [comment]
Huh, odd. I'm using IntelliJ IDEA 2022.1.3 which afaik Android Studio is based on. Maybe check for an update if it's been a while since you downloaded it.

Btw, (almost) all mods use Gradle as their build system, that's not the same thing as Maven. Both are build systems for Java (at least originally), though Gradle is (imo) much easier to configure (Maven uses xml files for configuration) and more powerful in general. Maven came first, and so Maven is not only a build tool but also a format for how to structure a repository from which one can download pre-built artifacts. And instead of completely reinventing the wheel, Gradle supports Maven repositories as the primary way to fetch artifacts too. That's why you see both terms being used in Gradle projects. But the client side is Gradle, so it's be Android Studio's Gradle plugin, and you're editing Gradle scripts.
