### ISSUE TITLE
Memory leak in 1.19.3

### ISSUE THREAD

**Issue by kindalas** [Johni0702/bobby#123]
I don't know a better way to reach out with issues.

I have noticed a memory leak when running bobbymod.

When the client is running and logged into a multiplayer world the memory usage in windows task manager gradually increases from what is normal 2.5-3.0 GB to 8+ GB when the client will crash.

I have also noticed that the bobby files are being saved differently in this version.

previously it would save into:

.bobby/worldIP/seed/minecraft/overworld or the_nether or the_end

now it saves into:

.bobby/unknown/seed/minecraft/overworld or the_nether or the_end

I suspect that these are related.

Let me know if you need any more of my configuration info.

I hope this helps.

Edit: Starlight somehow makes this worse. But adding Memory leak fix to my mods seems to have fixed or at least mitigated the issue.

**Comment by Johni0702** [comment]
There were no changes in the 1.19.3 version of bobby which could cause it to leak memory. I don't know of any place in bobby that could leak memory in general and have never had any such issues during multiple 6+ hours sessions of lots of running around.
If anything, I'd guess that it simple accelerates memory leaks present in other mods/drivers just by virtue of there being more chunks loaded at any one point in time.

Also, what are you doing ingame for memory to leak? Cause if you're just standing still and looking around, then bobby doesn't do anything.

Be careful about memory readings in the task manager, they may be misleading and do not necessarily mean what you think they do, see https://github.com/Johni0702/bobby/issues/117#issuecomment-1312667801.
Also be careful about drawing conclusions too quickly: Always test multiple times when you add/remove a mod and try to keep unrelated changes to a minimum. Starlight making a difference only makes sense in so far as that it speeds up lighting which may allow the leaky code to run faster / more often. Based on its wiki, Memory Leak Fix does not in fact fix
any relevant memory leaks, it merely fixes two leaks that happen in certain failure cases and "fixes" memory being held on to for longer than necessary but not in any way where it could accumulate over time.


All worlds being saved as `unknown` is definitely a bug though, and I already know the cause because I had a similar issue with another mod I maintain. I've opened a separate issue for it: #124

**Comment by kindalas** [comment]
Sorry about jumping the gun and blaming Bobby for the memory issues.

After sleeping I did a far better job of checking my setup and I discovered that Sodium 4.6 was the issue.

I am now reaching out to their dev team to see if it is my setup that is a problem or if there is a bug in sodium.
