### ISSUE TITLE
 Mixed world from minigame servers

### ISSUE THREAD

**Issue by EquityX** [Johni0702/bobby#126]
Bobby doesn't correctly recognize world change from minigames servers and you end up with a mixed world (by example go in hypixel skyblock in the hub, explore it then come back to your Island and see that far chunks are actually the hub chunks)

This doesn't happen with Farsight or Hold That Chunk.

**Comment by Johni0702** [comment]
That's because, as far as the client is aware, those are actually one and the same world. There's no way to differentiate between them. See also https://github.com/Johni0702/bobby/issues/72.

The reason this doesn't happen with Farsight/HTC is because they don't preserve any chunks across world changes at all.

**Comment by EquityX** [comment]
I see. Thank you for the information. Is it possible for you to add a configurable list of server ips that when joined, Bobby will disable itself? Or have a setting that disables Bobby for multiplayer only? Maybe add a keybind to enable & disable Bobby quickly?

All of these would help or "fix" the Mixed world issue. I personally don't have an issue with the mixed worlds, but it seems to bother a lot of players so I thought I might offer some suggestions. Sorry if I am annoying you & thank you for your hard work on this wonderful mod.

**Comment by sybenx** [comment]
The world could be checked for the percentage of identical chunks to match world data, creating a new data set for each unique world.
