### ISSUE TITLE
Bobby mod not loading chunks beyond 32 chunks

### ISSUE THREAD

**Issue by MqcCheeze** [Johni0702/bobby#137]
Even at bobby's default 64 chunk limit, the chunks beyond 32 chunks do not load, the fog gets removed however and the clouds do render at the specified chunks. In singleplayer, not opened to LAN

![image](https://user-images.githubusercontent.com/87596784/213884672-20f3cc70-551e-4c66-b529-007a01edcbb8.png)

![image](https://user-images.githubusercontent.com/87596784/213884729-4c0b865b-1c59-4adb-b75f-006b760c4b17.png)

![image](https://user-images.githubusercontent.com/87596784/213884761-d9cb998e-64f1-4048-933c-4791cd626e8f.png)
^ mods folder

[latest.log](https://github.com/Johni0702/bobby/files/10472909/latest.log)

**Comment by Johni0702** [comment]
That is correct. Bobby does not re-write the vanilla server's chunk management like C2ME does, and as such it cannot increase the server view distance beyond 32 (that's why the "Singleplayer Server View Distance" slider stops at 32).
You need to visit those chunks first so the server actually generates them, sends them to the client and bobby can cache them before bobby can load them from its cache when you move away from them again.
Not directly related but (presumably) the BetterF3 mod makes it difficult to tell if bobby is even functional in that first screenshot because it removes the line which bobby modifies to include its debug info (the line with `F:`, `L:` and `U:`).

**Comment by Colt44Magnum** [comment]
Even when I have the chunks cache they end up unloading at 32 chunks. I have bobby set to 1024 chunks

**Comment by Johni0702** [comment]
> Even when I have the chunks cached they end up unloading at 32 chunks. I have bobby set to 1024 chunks

Please open a separate issue and provide all the info for your case that OP has provided here (but without the fance F3 mod please, I want to see bobby's debug values in the F3 screen).

**Comment by Aonodensetsu** [comment]
same here, the chunks unload after leaving the area
1. bobby set to 64
2. travel in a direction
3. look back and see chunks disappearing
