### ISSUE TITLE
Considering backports to 1.19.2

### ISSUE THREAD

**Issue by Imzxhir** [Johni0702/bobby#149]
Description: I am asking this because many mod developers are refusing to update their mods to 1.19.3 or even 1.19.4 until 1.20 comes which leaves people to stay on 1.19.2 and missing out on critical or important updates which add features and fix bugs. I'm not saying the mods 'Bobby' refuses to update to 1.19.3 or 1.19.4 since it has already updated to those versions but I feel like from a user point of view, it can be annoying for them to miss out on new features and critical or normal bugs being fixed on new versions and then not being fixed on the original version that they were found in.

In my opinion, I think most mod developers should have 1.19.2 as a LTS type of release then 1.19.4 as a STS until 1.20 comes in which it doesn't matter since most if not all mod developers will most likely update their mods to 1.20.

I understand how much effort developers have to go through to backport changes back to 1.19.2 since they will most likely face issues or conflicts that are found within the code but I hope you atleast consider and think about it.

**Comment by Johni0702** [comment]
I have. I'm already maintaining two mods that support multiple MC versions and I do not wish to add another one to that list for multiple reasons. Among others:
- Your choice of 1.19.2 is more or less arbitrary. Why not support the latest (1.19.4) and the previous version (1.19.3). Why not support the latest version and the previous major version (1.18.2).
- Why should I be backporting, which is effectively wasted time once that version is eventually abandoned, rather than other people updating their mod, which results only in a small amount of extra work compared to updating to 1.20 directly (it'll generally be much easier to update from 1.19.4 to 1.20 compared to 1.19.2 to 1.20 because you've already done half the work).
- There haven't even been any major bug fixes in Bobby since 1.19.2. The most significant one is the fix for unloading block entities but block entities are completely disabled in bobby's default configuration anyway, and there's usually no reason to enable them in the first place. Maybe the 1.18->1.19 lighting data update bug; but if you on an old version, might as well go to the latest version or just stay on the old one if not all your mods have been updated yet.

**Comment by snoopchallenge** [comment]
1.8 backport i beg

(i know this probably wont be done but i put this here to encourage anyone who can and is thinking about doing it)
