### ISSUE TITLE
Bobby and Chisel and bits

### ISSUE THREAD

**Issue by L-mask** [Johni0702/bobby#157]
Good morning

I'm Trying to use Bobby in a Fabric mod pack which contains Chisel and bits.
Every time I join my server or even load a singleplayer world it is stuck at 100% loading, however my Player is already in the world.

Versions 
Minecraft 1.19.2
Bobby 4.0.1
Chisel and bits 1.3.135
Fabric api 0.76.0  (1.19.2)

Log
[latest.log](https://github.com/Johni0702/bobby/files/11303362/latest.log)

Awesome work Btw

**Comment by Johni0702** [comment]
From the looks of it this is a bug in mixin, and bobby+scena just happen to be an unlucky combo that triggers the bug (if you search for the error message on github, you can find about a dozen other combos that trigger the same bug).

I've opened an issue on Scena's issue tracker (first link above) because it would be trivial for them to work around the issue.
I've also opened an issue on fabric's issue tracker (second link above) and will close this issue in favor of it as I don't believe this to be an issue with Bobby itself.

FWIW it also doesn't seem to happen when using Quilt Loader 0.18.10 instead of Fabric Loader 0.14.19; whether that means that it's a fabric-mixin bug idk, could also just be that Quilt loads the mods in a different order which doesn't happen to trigger the bug.
