### ISSUE TITLE
Chunks doesn't load

### ISSUE THREAD

**Issue by GuntarsJ** [Johni0702/bobby#172]
I can put any render distance, over 32 chunks, and it won't load, it renders only 32 chunks

**Comment by kittokin** [comment]
that's how it works, if it let you render more than 32 chunks at full resolution, your PC would just lag terribly, all the other mods that allow you render beyond 32 just use some math generation using the seed of the world to render fake chunks or save a lower quality model for the blocks (Distant Horizons), only other mod that renders cached chunk like bobby is Farsight, but that one is also limited to 32 chunks.

**Comment by Johni0702** [comment]
No, that's very much not the case. Even the picture on the Modrinth/CurseForge page is using more than 32 chunks range.
It is true that the base game would struggle with higher render distances, but Sodium can easily pull 48 chunks at 120fps if you've got halfway decent hardware.

The two important things with Bobby of note here are:
1. You must have visited the distant chunks at some point in the past (with Bobby installed), otherwise there's no way for it to know what's there
2. If you're in Singleplayer, Bobby won't be active by default. You have to set the "Singleplayer View Distance Override" (name may be slightly different, I don't quite recall) in bobby's config to a non-zero value. Otherwise the integrated server will just load all chunks for real and there won't be anything to do for bobby (and the integrated server does indeed have a limit of 32).

**Comment by kittokin** [comment]
Sodium does not even allow you to increase the render beyond 32, as mentioned here: [sodium-fabric issue 178](https://github.com/CaffeineMC/sodium-fabric/issues/178) .
So unless the image author had added some other mod to do it or changed the config outside the game.

**Comment by Johni0702** [comment]
![](https://i.johni0702.de/NDwA9.png)
