### ISSUE TITLE
[Bug] Error with fake world

### ISSUE THREAD

**Issue by Rozbiynk** [Johni0702/bobby#192]
Skin shuffle also use it for render player model
![изображение](https://github.com/Johni0702/bobby/assets/95433246/0dbcffe6-d2ad-4d44-a41a-d4588dbf0165)
https://mclo.gs/MoME7CS
this issue on skin shuffle https://github.com/mineblock11/SkinShuffle/issues/33

**Comment by enjarai** [comment]
Co-author of SkinShuffle here. This issue seems to stem from `ClientChunkManagerMixin#bobbyInit` trying to create a `FakeChunkManager` for the chunkmanager of our subclass of `ClientWorld`, and failing because it isn't run on the main thread.

Would us creating our `ClientWorld` instance on the main thread be enough to fix this, or could other issues occur from this? Is there anything you need from our side to create more "proper" compatibility?

**Comment by mineblock11** [comment]
Any response to this? Would be willing to implement a fix relatively soon.

**Comment by Johni0702** [comment]
Should be fixed with Bobby 5.1.0.

**Comment by Rozbiynk** [comment]
can you make 1.20.1 version please?

**Comment by Spilya** [comment]
1.20.1 version please?

**Comment by IMB11** [comment]
Thank you @Johni0702, much appreciated :heart:
