### ISSUE TITLE
1.20.1 crash on startup

### ISSUE THREAD

**Issue by drathmorgh** [Johni0702/bobby#195]
Getting a crash in 1.20.1 un startup with optifabric/optifine.
No crash log only the normal log to show. 

It happens with every version of Optifine.
the few different API versions for 1.20.1.
with or without any other mod installed. 

So currently unuseable in a combo like it used to be. 

[latest.log](https://github.com/Johni0702/bobby/files/12136852/latest.log)

**Comment by drathmorgh** [comment]
Is this a bobby issue or an optifine / optifabric issue?

**Comment by Alixollo** [comment]
I'm having the exact same issue, hoping for a fix soon.

**Comment by catronomix** [comment]
Tried updating today and ran into the same problem, using bobby with optifabric and optifine

**Comment by StormDragon-DRG** [comment]
Having the same problem.

When BOBBY is not enabled, no issues.

When using the "Preview version of Optifine"/optifabric as well as the 1.20.1 version of Optifine/optifabric.  I have the same error message as OP.  and Minecraft crashes.

If I remove Bobby, and leave Optifine/optifabric. no crash.

If I remove Optifine/optifabric, and leave Bobby, no crash

I am using optifine because features of a couple of my texture packs rely on Optifine, and Sodium or other mods that replace optfine aren't compatible with the texture pack.

**Comment by CanadianJen** [comment]
I tinkered around and looked at the error codes and found that the problem is with “WorldRendererMixin” … if you remove that - it works and so far seems stable … 

unzip bobby-5.0.0 --> bobby.mixins.json --> delete "WorldRendererMixin", (its near the bottom, above the sodium. stuff) --> zip her back up & switch to a .json file ... TADA!

**Comment by drathmorgh** [comment]
Confirmed this has resolved the issue. 

On Windows, I used 7zip to open the package and copied the  bobby.mixins.json to the desktop, and then opened the file with VSStudio, can use notepad++ also, deleted the "WorldRendererMixin" line, saved and then dropped the "bobby.mixins.json" back into the package! I relaunched Minecraft and Booom no crash and all 100+ chunks loaded!! 
AMAZING

**Comment by StormDragon-DRG** [comment]
awesome!  confirmed that worked for me as well!
