### ISSUE TITLE
Dynamic World Management not working

### ISSUE THREAD

**Issue by MaledictYtb** [Johni0702/bobby#250]
Hey, 
I've tried the Dynamic World Management feature, but it seems to not work on 1.20.4 and 1.20.2 to. 
I've only been able to get it working by using your 1.19.4 build here : https://github.com/Johni0702/bobby/issues/72#issuecomment-1518831417

**Comment by JurassikLizard** [comment]
Can confirm this seems to happen in multiplayer for me
For more detail -
It seems as though it works, but upon rejoining, all previous chunk data is reset
It also constantly spams a message about running "/bobby upgrade"

**Comment by Johni0702** [comment]
It obviously works for me on those versions, otherwise I wouldn't have published it, so I need more info than just "it doesn't work".

> It seems as though it works, but upon rejoining, all previous chunk data is reset

After re-joining, what's the output of `/bobby worlds full`.
Ideally attach the log file, the output in the chat window may be difficult to read.

> It also constantly spams a message about running "/bobby upgrade"

So.. did you do it? Again, what's the output of above debug command?

Do you have a fallback world configured? If so, that needs to be updated via MC's upgrade world functionality.

**Comment by MaledictYtb** [comment]
Hi, here's a video and the output of /bobby words full. I have the problem on Hypixel and arcticmc, as well as Cubecraft in which each world has a different name. 

https://youtu.be/UA7NbjDn3Jg

**Comment by KrisAphalon** [comment]
I think https://github.com/Johni0702/bobby/issues/250#issuecomment-2073420955 might be different issue.

I was able to reproduce the issue @MaledictYtb has shown and I created a merge request with a fix.
