### ISSUE TITLE
Huge delay in chunk rendering with Bobby 1.20

### ISSUE THREAD

**Issue by Xenapte** [Johni0702/bobby#265]
![](https://github.com/Johni0702/bobby/assets/17661805/29738a99-4f26-4acc-a655-bfcbe7b2e04d)
![](https://github.com/Johni0702/bobby/assets/17661805/90118694-9763-4263-b266-b57569c99f66)

On servers set to a low render distance with Bobby 1.20, the game experiences long delays in rendering new chunks once a certain number of chunks have been loaded. It's especially apparent when flying around with an elytra; you can easily fly into chunks that won't render for a while, even though technically they are already loaded.

I've never experienced this on 1.19 with a similar mod setup, but with 1.20 I have to press F3+A constantly to reload all rendered chunks.
Don't know if this is really a Bobby issue (there's indeed a known bug at [[MC-261495]](https://bugs.mojang.com/browse/MC-261495) with vanilla game, but it's confirmed to exist in 1.19 too), but I've been unable to produce it on vanilla.

**Comment by Johni0702** [comment]
Seems quite likely that this is indeed just the issue you linked. Quite possible that 1.19 just behaves slightly different so that it doesn't happen for you there.
I'd highly recommend using [Sodium](https://modrinth.com/mod/sodium) with Bobby (and just in general too). Among other things it also completely rewrites chunk scheduling, and should almost certainly fix that issue.

**Comment by Xenapte** [comment]
This issue happens regardless of if I'm using sodium with bobby
