### ISSUE TITLE
Bobby Fallback

### ISSUE THREAD

**Issue by Minnewit** [Johni0702/bobby#273]
Hey, I'm sorry if this question was answered already but I cannot really find a full Noob Friendly guide on how to activate the bobby fallback mechanic.
I know, that I have to rename a World folder to Bobby-Fallback but does this have to be like the same world as the server I'm trying to use it on and where can I find this world folder.
Again: really, really sorry for the stupid question but I'm really not that much into MC Modding.
Thank You :)

**Comment by PitchBlackNights** [comment]
1. To use a world as a Bobby Fallback, you just have to rename the folder to `bobby-fallback`.
2. There are many places you can find the world folder. If you are just using the default Minecraft Launcher it will be located at `C:\Users\{USERNAME}\AppData\Roaming\.minecraft\saves`. If you are using a third-party launcher like Curseforge, Modrinth, MultiMC, Prism, etc. then there should be a button somewhere that will take you to the `.minecraft` folder for that instance.
3. As for if the world has to be the same? No, it does not need to be the same for Bobby to use it. HOWEVER, if the world is not the same as on the server, you will see the wrong chunks. (E.g, a chunk of a plains biome instead of a desert)

Does this answer your questions?

**Comment by Minnewit** [comment]
I think I get it now.. 
So in order to use it on a survival server I first need to find out the Seed of that paticular server, ceate a singleplayer world with that Seed and rename its save folder to bobby-fallback. 
Is that right?

**Comment by PitchBlackNights** [comment]
@Minnewit Yes, you will need to retrieve either the world file for the server, or you could make a world with the same seed (You just won't see any edits to the terrain until you load those chunks).
