### ISSUE TITLE
Is bobby compatible with distant horizon？

### ISSUE THREAD

**Issue by AshdoII** [Johni0702/bobby#289]
I have been using bobby and distant horizon on my server. It did not crash but I want to know if they all did different works   or they have simmilar functions.

**Comment by Fa1ki** [comment]
Bobby saves the chunks on your computer, allowing you to reach the view distance set in Minecraft. This enables you to see beyond the server's view distance. Distant Horizons, on the other hand, allows you to see beyond the view distance set in Minecraft.

**Comment by Johni0702** [comment]
Not sure if they're officially compatible. At least I've never tested Bobby with Distant Horizons.
They do indeed serve roughly similar purposes, the primary difference being that Distant Horizons simplifies geometry that's further away from you (because ideally the blocks are so small that you wouldn't be able to tell the difference) and therefore requires a custom renderer and is much more complex. Bobby on the other hand simply loads everything the regular way, so even with a zoom mod you'll always be able to make out all the details, but it'll use much more resources for greater render distances, but it's also much simpler and naturally more compatible with other mods.
And despite doing roughly the same thing, it may still make sense to use them both at the same time: Distant Horizons to get huge render distances, and Bobby to still get full details within some smaller (but still bigger than vanilla) distance.
