### ISSUE TITLE
Chunks are weird. Probably mod compatibility, but idk.

### ISSUE THREAD

**Issue by electricsteve** [Johni0702/bobby#322]
I don't know if it's a mod incompatibility, but it could not be.
Here is the issue:
[video (streamable)](https://streamable.com/50j53n)
If the issue isn't clear right away I will go binary testing tomorrow (removing half mods over and over).

**Comment by Sato-Devs** [comment]
Chunks not loading just started affecting players using my pack as well. Removing bobby fixed it.

**Comment by Johni0702** [comment]
Chunks not being visible when there's missing chunks between you and them is expected behavior, that's the game optimizing which chunks it needs to bother drawing. Usually not a problem in vanilla because the loaded chunks are always a rectangle; bit unfortunate for bobby but not much that can be done without rewriting half the chunk renderer.

The chunks which don't load when you get close to them are suspicious though. Would need a way to reproduce to debug it though, ideally with as few mods as strictly required.

**Comment by electricsteve** [comment]
This was so long ago I don't really play with bobby anymore.
