### ISSUE TITLE
Game freezes then crashes when enabling more than 32 chunks.

### ISSUE THREAD

**Issue by Fainthful** [Johni0702/bobby#340]
Maybe something is wrong with my pc or minecraft. 
[2024-11-20-3.log](https://github.com/user-attachments/files/17822544/2024-11-20-3.log)
[latest.log](https://github.com/user-attachments/files/17822566/latest.log)

**Comment by Johni0702** [comment]
The attached logs do not show any crashes.
If Windows says that the game isn't responding, that doesn't necessarily mean that it's crashed, it may just be busy for a while for some reason.

If you can provide a proper crash log, I'll see if I can easily see the other, otherwise I'm afraid I'm no longer providing support for 1.19 and would recommend you update to a modern version.

**Comment by Fainthful** [comment]
It was a 1.19 version issue, fixes itself in later ones.
