### ISSUE TITLE
[Feature Request] Config option to differentiate between vanilla chunks and bobby chunks

### ISSUE THREAD

**Issue by UndeadKitten** [Johni0702/bobby#41]
I'd find it useful for PVP servers so you don't get tricked into thinking there aren't any players in the distance, but then they suddenly pop in once they reach the vanilla chunks. Not necessary to implement right now since the bug with starlight #18 is inadvertently what I'm looking for, but would appreciate it if you implement something like it if/when the bug with starlight is fixed after it leaves beta.

**Comment by mikenrafter** [comment]
Perhaps a light red/gray overlay, or dot in the sky of bobby chunks, desaturation, a border, etc?

**Comment by Johni0702** [comment]
That's all very much out of scope in my opinion. As far as the game is concerned, fake chunks are just like real chunks. Bobby doesn't touch rendering at all at the moment.
Anything which modifies the way chunks are rendered must either be baked in and therefore require a full chunk reload (F3+A) or, if it's dynamic, is pretty much guaranteed to break the moment you add Sodium (cause it renders multiple chunks all at the same time) or Iris (cause shaders don't know what bobby's doing).
So this would basically have to be just something which is rendered in addition to the regular rendering, i.e. the dot in the sky or a border or the like. The dot has the disadvantage that it's probably quite hard to correlate with the terrain far below, so having some sort of border drawn on all fake-real chunk edges is probably the best solution.

Definitely something I'll consider in the future because it would also be useful just for debugging stuff.

**Comment by mikenrafter** [comment]
Perhaps instead of rendering a dot in the sky, or a border, just modify the chunk data to include some kind of marker, perhaps a powered redstone lamp, 5 blocks above whatever the heightmap gives you, and in the center of the chunk?

**Comment by Johni0702** [comment]
I thought about a bunch of things, tried a few and eventually decided to go for a less extreme "bobby+starlight bug" effect (i.e. mess with the lighting data).

I played a bit with the values, trying to find ones that are noticeable if you know to look for them but not strong enough to look outright broken, and settled on +5 to block light (so the chunks are lighter when it's night) and -3 to -10 to sky light depending on your brightness setting (so they're darker during the day).

Daytime (that's not a swamp! it changes when you move):
![](https://i.johni0702.de/ukUae.png)

Nighttime:
![](https://i.johni0702.de/boeQh.png)

You want to play with Sodium, so the chunks update in time if you're moving quickly. Vanilla is a bit slow to update them.
Also note that changing your brightness setting won't update the sky light of fake chunks which are already loaded, you'll have to disable and re-enable the feature, a quick re-log will also do.
