### ISSUE TITLE
Chunks do not have time to load on drawing above 32 chunks

### ISSUE THREAD

**Issue by MiFliK** [Johni0702/bobby#47]
When playing on a drawing above 32 chunks in a single world, chunks often do not have time to load
Here is a visual video dimostration

Also, as a possible correction in the view-distance-overwrite = 32 parameter, add the ability to set more than 32 chunks, namely as many as specified in the max render
since this is a single player game this can be completely fixed
I really hope that this can be fixed
https://youtu.be/0qahY_rbFRU

**Comment by Johni0702** [comment]
The whole point of this mod is to draw chunks which the server (either a real one or the integrated one) does not send. You need to have visited those chunks once in the past for the mod to have any way to do that.

Increasing the server view distance (even for the integrated server) is not what this mod is about. The reason the overwrite exists is to allow for the server view distance to be **lower** than the render distance (i.e. reduce the performance impact of the server).
The 32 limit is inherent in how the game does chunk tracking since 1.14 and cannot easily be changed.
