### ISSUE TITLE
[Question] Is an 1.18 version planned ?

### ISSUE THREAD

**Issue by ALENI27** [Johni0702/bobby#58]
1.18 just got released today so. Is a 1.18 version planned? If yes, is there a time estimation before the release?

**Comment by Johni0702** [comment]
Yes. Dunno when I'll get to it though, probably some time next week or the one thereafter.
I might be able to post a dev version here within the next few days, I just don't have the time to properly test it (i.e. playing the game for an extended period of time to make sure there are no lag spikes, etc.).

**Comment by ALENI27** [comment]
I can do the test part if you want, you can contact me on discord 'ALENI27#9161' if you need someone to test.

**Comment by c1oneman** [comment]
Any update on this?

**Comment by EysseW** [comment]
I am waiting too. Not trying to set preasure though, just wanna let you know you mod is loved

**Comment by ByteBeamer** [comment]
Yeah, this mod is essential on Minecraft servers with low render distance.

**Comment by bandisast** [comment]
I can also do the test part, if needed!

**Comment by Johni0702** [comment]
Alright, here's the dev version I was talking about: https://i.johni0702.de/bobby-3.0.0-SNAPSHOT.jar (source commit: 75a3486)
Be sure to back up your `.bobby` folder if you're not using a separate minecraft folder for each version. Please let me know of any issues you find and give this message a thumbs up if you've been testing it for any substantial amount of time.

It should be compatible with Sodium 0.4.0-alpha5; future versions may or may not work depending on what was changed.

This version also has support for upgrading old caches to the new Minecraft version. I've tried to do this on demand as chunks were being loaded but that turned out to be horrible for performance, so instead you'll have to run `/bobby upgrade` which will upgrade all of them at once. It'll still be bad for performance but only for a few minutes and you decide when to do it.
For reference of how long it might take: Upgrading my 225k chunks (2944 region files) Wynncraft cache took roughly ten minutes when I wasn't doing anything else (though beware that a good amount of those chunks were probably just void and therefore quick to upgrade).
Also don't be alarmed by the initial number of total chunks to be processed. It is often a huge overestimate because it is based purely on the amount of region files (each is 32x32 chunks) but often not all of those chunks are present. The number will be corrected downwards whenever a region file is actually read.

**Comment by ALENI27** [comment]
Just tested id. It seems to be working well, but when I break block too fast a lot of block are not sync with server (I see that a block is missing and for the server this block is not missing). It does not happen without bobby.

**Comment by ST-DDT** [comment]
I also got issues with it (For me breaking a block causes it to reappear for a few seconds.), but I'm not sure what the exact reason is.
 
- My OptiFabric setup
- Or a slightly laggy server (removing this mod reduces the reappear time by a lot (<1s))

By switching from optifabric to sodium, and migrating the server (and thus eliminating most of the TPS issues), the issue no longer appears.

**Comment by bandisast** [comment]
The above issues might be related to your render/simulation distance or the server's render/simulation distance. On a server with very low render distance (6 chunks) I could not notice any of the aforementioned issues above or under the ground. Overall it's been a smooth experience and I couldn't notice any worthwhile issues even after several hours on that server. I should probably investigate whether the aforementioned issue will appear in my singleplayer worlds because of the higher render distance.

**Comment by Johni0702** [comment]
Could both of you check if the behavior still happens with no other mods and:
a) same render distance as before (if the game can take it)
b) render distance set just slightly above server view distance (the `F:` value in the F3 screen should be relatively small, roughly 4x render distance)
c) render distance set to server view distance (the `F:` value in the F3 screen should be 0)
d) render distance set to 2 (the `F:` value in the F3 screen should be 0)
e) normal render distance with bobby installed but disabled via its config (there should be no `F:` value in the F3 screen)
e) normal render distance without bobby installed (just to double check)

Reconnect between each attempt and configure everything while your are disconnected. If you go in order, there'll be progressively less of bobby active, and once you find one which doesn't have the issue, you can skip the remainder cause they'll be fine as well.

Just for the record: Optifine is not something I'll support. It's proprietary and has been a major PITA for literal years now. If it works, it works; if it doesn't, it's up to its author to fix it.

**Comment by Biscuts511** [comment]
the lack of optifine support makes sence, will sodium+iris be supported?

**Comment by ST-DDT** [comment]
I use this mod with sodium with iris shaders and a chunk render distance of 100 for a few hours (close to one day playtime) now without issues.

I was unable to verify my previous ghost block issue as the server no longer has TPS lags/issues.

**Comment by ALENI27** [comment]
> Just tested it. It seems to be working well, but when I break block too fast a lot of block are not sync with server (I see that a block is missing and for the server this block is not missing). It does not happen without bobby.

So regarding what I said, I tryed to remove bobby, restart my game and then restarting my game with bobby and no more ghost s blocks problems. Idk if it was little bug of bobby or if it has nothing to do with it.

I sometimes  has some small light problem, (it take like 10 sec to light up some chunks (it's very rare, like 1 in 100 chunks)).

**Comment by 31j** [comment]
> the lack of optifine support makes sence, will sodium+iris be supported?

Sodium & iris historically have not been issues, and with the current alpha don't appear to be either. Phosphor is usually fine as well, but Starlight is a different story
