### ISSUE TITLE
Causing crashing when 1+ month using the mod

### ISSUE THREAD

**Issue by DoTrONoL** [Johni0702/bobby#59]
Causing crashing when 1+ month. Minecraft 1.17.1

Something makes my game crash when I switch in the server's world quickly. Also when you have much time using the mod makes the Xaero's WorldMap mod crash your game.

I was suffering from crashes around 2 months ago and today it got intensified. I've contacted Xaero to report to him this issue, but before I do it I solved the problem by deleting all the existing chunks in Bobby, then all the WorldMap bugs were solved by only deleting Bobby chunks... This is annoying cuz I have to rerender all those chunks and repeat it every time to don't get crashed. Hope you fix it.

**Comment by Johni0702** [comment]
If your game is crashing, please provide the crash report and ideally the whole `.minecraft/logs/latest.log` file, otherwise there is nothing I can do.
There is nothing in this mod which would make it change behavior after any time of use. I've been using it for far longer than a month (about 300 hours play time) and have had no such issues.

As for Xaero's WorldMap, its author has decided to keep their mod closed off, so there's nothing I can help you with there and you're entirely at the mercy of its author.

**Comment by DoTrONoL** [comment]
Well, I've contacted him and he said:

"I don't see how the world map mod would ever try to look up the biome for out-of-bounds coordinates, so something must be happening elsewhere that is out of my control"
"Not necessarily Bobby either though"

And about the log, I have to search for it cuz it's old, but the newest is resumed in this crash report below.

Also here is the crash report:
https://pastebin.com/C9K3ua6S

**Comment by Johni0702** [comment]
As said above, unless they tell me exactly what the issue is, there is nothing I can do to fix it because they do not allow anyone else to look at their code but there is a whole bunch of their code in the error.

Also, in case you didn't know, GitHub has an edit history. And what you did looks very much like you just flat out lied about what they said, given what you claimed they said when you originally posted that message.
