### ISSUE TITLE
[Feature] Async chunk loading

### ISSUE THREAD

**Issue by mastermc05** [Johni0702/bobby#74]
Allow async chunk loading so i won't lag that much when teleporting

**Comment by Johni0702** [comment]
Chunk loading has been async since 0.2.0, and highly optimized with spreading out of main thread work across multiple frames since 1.0.0 (specifically with the goal of not causing any noticeable impact after teleports at 48-96 render distance), and with optimizations to the lighting engine since 1.1.0 which was the last source of teleport related lag.
If you're using one of those ancient versions, you should update. If you're not, then it's almost certainly not Bobby causing the lag.

I'd recommend you use a profiler (e.g. [Spark](https://spark.lucko.me/) to capture a profile at the time you experience lag. Try to minimize the lag-free time during profiling so it's apparent what's lag vs just normal game.
