### ISSUE TITLE
joining world

### ISSUE THREAD

**Issue by unknown-error42** [Johni0702/bobby#97]
when bobby is enabled and you attempt to join a server it will get stuck on the joining world screen
1.18.1 fabric

**Comment by P529** [comment]
I have a similar issue, I wasn't really sure if I should open a new issue for it, but when i join a server I get stuck on "laoding terrain ... ". That only happens if I have a big folder of cached server.

**Comment by forshale** [comment]
I am also getting this issue.  However, I'm not sure what's happening because it worked perfectly yesterday.  I checked for mod conflicts and I tried with bobby alone, and with only bobby it just doesn't work, meaning it's not a mod conflict. 
After some thinking about what I did last night, I remember changing the render distance from 32 down to 16 but outside of the actual server and in the main menu settings. This is the only thing I could remember doing.  I tried restarting MC several times, I've restarted my PC about 3 times, and have reinstalled the specific mod 3.1.1 version 3 times as well.

**Comment by Johni0702** [comment]
Closing under the assumption that it's file corruption for the first two posters as well.

If you're reading this because you are running into a similar issue, please open a separate GitHub issue and be sure to include as much info as possible (at the very least the `latest.log` file).
